// Generated by CoffeeScript 1.4.0
(function() {
  var coffee, compile, fs, fsx, path, uglify;

  process.chdir(__dirname);

  fs = require("fs");

  path = require("path");

  coffee = require("coffee-script").compile;

  uglify = require("uglify-js").minify;

  fsx = require("../src/lib/filehelpers");

  compile = function(srcfile) {
    var fi;
    fi = fsx.fileInfo(srcfile);
    if (fi.fileext === ".coffee") {
      fsx.mkdirp(fi.targetfullpath, 0x1ff);
      return fs.writeFileSync(fi.targetpath, uglify(coffee(fs.readFileSync(srcfile, "UTF-8")), {
        fromString: true
      }).code);
    }
  };

  console.log("Clearing build directory...");

  fsx.mkdirp("../build", 0x1ff);

  fsx.clearDir("../build");

  fsx.mkdirp("../build/logs", 0x1ff);

  fsx.mkdirp("../build/procs", 0x1ff);

  console.log("Building...");

  compile("../src/server.coffee");

  fsx.walk("../src/config", fsx.copy);

  fsx.walk("../src/views", fsx.copy);

  fsx.walk("../src/web", fsx.copy);

  fsx.walk("../src/routes", compile);

  fsx.walk("../src/lib", compile);

  fsx.copy("../package.json", "../build/package.json");

}).call(this);
